#!/bin/bash

inputchao="xin chào"

chao=("hi" "Chào bạn" "Xin chào")
random_chao=$(($RANDOM % ${#chao[@]}))

case $1 in
    *"chào"* )
       echo "${chao[random_chao]}"
        ;;
        *"hi"* )
       echo "${chao[random_chao]}"
        ;;
        
    *)
        echo "j tr z"
        ;;
        
        "get_start")
        echo -e "\e[34mLoad bot"
sleep 1
echo -e "\e[34mLoad data in file github"
sleep 1
echo -e "\e[34mDone"
sleep 1
echo -e "\e[34mStart"
sleep 1
echo -e "\e[34mCmd"
        ;;
        
esac
